export interface ProductItem {
  id: string;
  title: string;
  slug: string;
  description: string;
  price: number;
  originalPrice?: number;
  category: "footwear" | "outerwear" | "apparel" | "accessories" | "limited-drop";
  gender?: "unisex" | "men" | "women";
  sizes: string[];
  colors: string[];
  images: string[];
  featuredImage: string;
  isFeatured: boolean;
  isNewDrop: boolean;
  inStock: boolean;
  stockCount: number;
  rating: number;
  reviewsCount: number;
  tags: string[];
}

export const INITIAL_PRODUCTS: ProductItem[] = [
  {
    id: "astra-jordan-rev",
    title: "Astra Jordan Air Rev",
    slug: "astra-jordan-air-rev",
    description: "Crossing hardwood comfort with off-court flair. '80s-inspired aerospace construction, bold kinetic details and nothin'-but-net style.",
    price: 69.99,
    originalPrice: 120.0,
    category: "footwear",
    gender: "unisex",
    sizes: ["US 7", "US 8", "US 9", "US 10", "US 11", "EU 38", "EU 40", "EU 42", "EU 44"],
    colors: ["Black and White", "Obsidian / Violet", "Pure Titanium"],
    images: [
      "https://cdn.21st.dev/assets/mirror/b5/b53e247c16c9009c0c84b479f179878b30db90aa2b6c483b5317f9c3cc185ba1.png",
      "https://images.unsplash.com/photo-1552346154-21d32810aba3?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=1000&q=80",
    ],
    featuredImage: "https://cdn.21st.dev/assets/mirror/b5/b53e247c16c9009c0c84b479f179878b30db90aa2b6c483b5317f9c3cc185ba1.png",
    isFeatured: true,
    isNewDrop: true,
    inStock: true,
    stockCount: 28,
    rating: 4.9,
    reviewsCount: 142,
    tags: ["Sneakers", "Bestseller", "Kinetic Sole"],
  },
  {
    id: "astra-cyber-runner",
    title: "Astra Matrix Cyber Runner",
    slug: "astra-matrix-cyber-runner",
    description: "Ultralight carbon-fiber reinforced athletic silhouette engineered for high-velocity metropolitan movement with dual-density foam dampening.",
    price: 189.0,
    originalPrice: 240.0,
    category: "footwear",
    gender: "unisex",
    sizes: ["US 8", "US 9", "US 10", "US 11", "EU 41", "EU 42", "EU 43"],
    colors: ["Cyber Silver", "Stealth Black", "Neon Violet"],
    images: [
      "https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=1000&q=80",
    ],
    featuredImage: "https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=1000&q=80",
    isFeatured: true,
    isNewDrop: true,
    inStock: true,
    stockCount: 15,
    rating: 5.0,
    reviewsCount: 88,
    tags: ["Carbon Fiber", "Running", "Limited"],
  },
  {
    id: "astra-silk-hoodie",
    title: "Astra Heavyweight Raw Silk Hoodie",
    slug: "astra-heavyweight-raw-silk-hoodie",
    description: "520 GSM custom milled heavyweight organic cotton infused with raw silk threads. Oversized boxy silhouette with dropped shoulders and concealed seam pockets.",
    price: 145.0,
    originalPrice: 195.0,
    category: "apparel",
    gender: "unisex",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Obsidian Onyx", "Slate Grey", "Violet Mist"],
    images: [
      "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1509967419530-da38b4704bc6?auto=format&fit=crop&w=1000&q=80",
    ],
    featuredImage: "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=1000&q=80",
    isFeatured: true,
    isNewDrop: true,
    inStock: true,
    stockCount: 42,
    rating: 4.8,
    reviewsCount: 96,
    tags: ["Heavyweight", "Apparel", "Organic Cotton"],
  },
  {
    id: "astra-monolith-trench",
    title: "Astra Monolith Tailored Trench",
    slug: "astra-monolith-tailored-trench",
    description: "Architectural structured overcoat crafted from waterproof technical gabardine. Features magnetic storm flap fastening and internal sling harness.",
    price: 320.0,
    originalPrice: 450.0,
    category: "outerwear",
    gender: "unisex",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Deep Pitch Black", "Titanium Grey"],
    images: [
      "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1000&q=80",
    ],
    featuredImage: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=1000&q=80",
    isFeatured: true,
    isNewDrop: false,
    inStock: true,
    stockCount: 12,
    rating: 4.95,
    reviewsCount: 54,
    tags: ["Couture", "Outerwear", "Waterproof"],
  },
  {
    id: "astra-kinetic-cargo",
    title: "Astra Kinetic Articulated Cargos",
    slug: "astra-kinetic-articulated-cargos",
    description: "Ergonomic 8-pocket modular trousers built with water-repellent Schoeller technical ripstop, 3D articulated knee panels, and Fidlock magnetic buckle adjusters.",
    price: 165.0,
    originalPrice: 210.0,
    category: "apparel",
    gender: "unisex",
    sizes: ["30", "32", "34", "36"],
    colors: ["Anthracite", "Tactical Olive", "Shadow Black"],
    images: [
      "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1517445312882-bc9910d016b7?auto=format&fit=crop&w=1000&q=80",
    ],
    featuredImage: "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&w=1000&q=80",
    isFeatured: false,
    isNewDrop: true,
    inStock: true,
    stockCount: 35,
    rating: 4.7,
    reviewsCount: 62,
    tags: ["Modular", "Techwear", "Cargo"],
  },
  {
    id: "astra-high-top-titan",
    title: "Astra High-Top Titan Leather Boot",
    slug: "astra-high-top-titan-leather-boot",
    description: "Full-grain Italian calfskin high-top sneaker boot fused with a geometric Vibram sawtooth lug sole and brushed titanium eyelets.",
    price: 240.0,
    originalPrice: 290.0,
    category: "footwear",
    gender: "unisex",
    sizes: ["US 8", "US 9", "US 10", "US 11", "US 12"],
    colors: ["Triple Black", "Bone White"],
    images: [
      "https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1595341888016-a392ef81b7de?auto=format&fit=crop&w=1000&q=80",
    ],
    featuredImage: "https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=1000&q=80",
    isFeatured: true,
    isNewDrop: false,
    inStock: true,
    stockCount: 18,
    rating: 4.9,
    reviewsCount: 77,
    tags: ["Italian Calfskin", "Vibram Sole", "Luxury Boot"],
  },
  {
    id: "astra-oversized-tee",
    title: "Astra 'Aether' Graphic Oversized Tee",
    slug: "astra-aether-graphic-oversized-tee",
    description: "300 GSM luxury combed jersey tee featuring high-density embossed ASTRA kinetic artwork, ribbed crewneck collar, and vintage enzyme wash finish.",
    price: 55.0,
    originalPrice: 75.0,
    category: "apparel",
    gender: "unisex",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Acid Black", "Chalk White", "Electric Plum"],
    images: [
      "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=1000&q=80",
    ],
    featuredImage: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=1000&q=80",
    isFeatured: false,
    isNewDrop: true,
    inStock: true,
    stockCount: 60,
    rating: 4.85,
    reviewsCount: 110,
    tags: ["Oversized", "Vintage Wash", "Streetwear"],
  },
  {
    id: "astra-leather-crossbody",
    title: "Astra Minimalist Leather Crossbody Bag",
    slug: "astra-minimalist-leather-crossbody-bag",
    description: "Compact sculptured crossbody pouch handcrafted from vegetable-tanned nappa leather with matte black hardware and quick-release aircraft buckle.",
    price: 110.0,
    originalPrice: 140.0,
    category: "accessories",
    gender: "unisex",
    sizes: ["One Size"],
    colors: ["Matte Obsidian", "Silver Chrome"],
    images: [
      "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=1000&q=80",
    ],
    featuredImage: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=1000&q=80",
    isFeatured: false,
    isNewDrop: true,
    inStock: true,
    stockCount: 22,
    rating: 4.9,
    reviewsCount: 39,
    tags: ["Accessories", "Nappa Leather", "Modular"],
  },
];
